2022-01-05 21:18:56,811 INFO    MainThread:26892 [wandb_setup.py:_flush():71] setting env: {}
2022-01-05 21:18:56,811 INFO    MainThread:26892 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-05 21:18:56,811 INFO    MainThread:26892 [wandb_init.py:_log_setup():371] Logging user logs to D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\wandb\run-20220105_211856-3if0dwkg\logs\debug.log
2022-01-05 21:18:56,811 INFO    MainThread:26892 [wandb_init.py:_log_setup():372] Logging internal logs to D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\wandb\run-20220105_211856-3if0dwkg\logs\debug-internal.log
2022-01-05 21:18:56,812 INFO    MainThread:26892 [wandb_init.py:init():404] calling init triggers
2022-01-05 21:18:56,812 INFO    MainThread:26892 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-05 21:18:56,813 INFO    MainThread:26892 [wandb_init.py:init():460] starting backend
2022-01-05 21:18:56,813 INFO    MainThread:26892 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2022-01-05 21:18:56,817 INFO    MainThread:26892 [backend.py:ensure_launched():216] starting backend process...
2022-01-05 21:18:56,934 INFO    MainThread:26892 [backend.py:ensure_launched():222] started backend process with pid: 35296
2022-01-05 21:18:56,935 INFO    MainThread:26892 [wandb_init.py:init():469] backend started and connected
2022-01-05 21:18:56,937 INFO    MainThread:26892 [wandb_init.py:init():533] updated telemetry
2022-01-05 21:18:56,940 INFO    MainThread:26892 [wandb_init.py:init():563] communicating current version
2022-01-05 21:18:58,005 INFO    MainThread:26892 [wandb_init.py:init():568] got version response 
2022-01-05 21:18:58,005 INFO    MainThread:26892 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-05 21:19:28,007 INFO    MainThread:26892 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-01-05 21:19:28,007 ERROR   MainThread:26892 [wandb_init.py:init():583] backend process timed out
2022-01-05 21:19:28,007 ERROR   MainThread:26892 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-01-05 21:19:37,379 INFO    MainThread:26892 [wandb_init.py:teardown():219] tearing down wandb.init
