2022-01-05 21:05:40,668 INFO    MainThread:31796 [wandb_setup.py:_flush():71] setting env: {}
2022-01-05 21:05:40,668 INFO    MainThread:31796 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-05 21:05:40,668 INFO    MainThread:31796 [wandb_init.py:_log_setup():371] Logging user logs to D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\wandb\run-20220105_210540-vpr2dq9c\logs\debug.log
2022-01-05 21:05:40,668 INFO    MainThread:31796 [wandb_init.py:_log_setup():372] Logging internal logs to D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\wandb\run-20220105_210540-vpr2dq9c\logs\debug-internal.log
2022-01-05 21:05:40,669 INFO    MainThread:31796 [wandb_init.py:init():404] calling init triggers
2022-01-05 21:05:40,669 INFO    MainThread:31796 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-05 21:05:40,670 INFO    MainThread:31796 [wandb_init.py:init():460] starting backend
2022-01-05 21:05:40,670 INFO    MainThread:31796 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2022-01-05 21:05:40,675 INFO    MainThread:31796 [backend.py:ensure_launched():216] starting backend process...
2022-01-05 21:05:40,772 INFO    MainThread:31796 [backend.py:ensure_launched():222] started backend process with pid: 34124
2022-01-05 21:05:40,772 INFO    MainThread:31796 [wandb_init.py:init():469] backend started and connected
2022-01-05 21:05:40,775 INFO    MainThread:31796 [wandb_init.py:init():533] updated telemetry
2022-01-05 21:05:40,777 INFO    MainThread:31796 [wandb_init.py:init():563] communicating current version
2022-01-05 21:05:41,880 INFO    MainThread:31796 [wandb_init.py:init():568] got version response 
2022-01-05 21:05:41,880 INFO    MainThread:31796 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-05 21:06:11,880 INFO    MainThread:31796 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-01-05 21:06:11,880 ERROR   MainThread:31796 [wandb_init.py:init():583] backend process timed out
2022-01-05 21:06:11,880 ERROR   MainThread:31796 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-01-05 21:06:11,890 ERROR   MainThread:31796 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\wandb_init.py", line 931, in init
    run = wi.init()
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\wandb_init.py", line 596, in init
    backend.cleanup()
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\backend\backend.py", line 245, in cleanup
    self.interface.join()
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 458, in join
    super().join()
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\interface\interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "D:\anaconda\envs\myprompt\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
