2022-01-05 21:26:38,440 INFO    MainThread:35360 [wandb_setup.py:_flush():71] setting env: {}
2022-01-05 21:26:38,440 INFO    MainThread:35360 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-05 21:26:38,441 INFO    MainThread:35360 [wandb_init.py:_log_setup():371] Logging user logs to D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\wandb\run-20220105_212638-11zqevfl\logs\debug.log
2022-01-05 21:26:38,441 INFO    MainThread:35360 [wandb_init.py:_log_setup():372] Logging internal logs to D:\GitHub\OnePunch\OnepunchPrompt_for_new_transformers\wandb\run-20220105_212638-11zqevfl\logs\debug-internal.log
2022-01-05 21:26:38,442 INFO    MainThread:35360 [wandb_init.py:init():404] calling init triggers
2022-01-05 21:26:38,442 INFO    MainThread:35360 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-05 21:26:38,442 INFO    MainThread:35360 [wandb_init.py:init():460] starting backend
2022-01-05 21:26:38,442 INFO    MainThread:35360 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2022-01-05 21:26:38,447 INFO    MainThread:35360 [backend.py:ensure_launched():216] starting backend process...
2022-01-05 21:26:38,565 INFO    MainThread:35360 [backend.py:ensure_launched():222] started backend process with pid: 35588
2022-01-05 21:26:38,566 INFO    MainThread:35360 [wandb_init.py:init():469] backend started and connected
2022-01-05 21:26:38,569 INFO    MainThread:35360 [wandb_init.py:init():533] updated telemetry
2022-01-05 21:26:38,571 INFO    MainThread:35360 [wandb_init.py:init():563] communicating current version
2022-01-05 21:26:39,571 INFO    MainThread:35360 [wandb_init.py:init():568] got version response 
2022-01-05 21:26:39,571 INFO    MainThread:35360 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-05 21:27:09,572 INFO    MainThread:35360 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-01-05 21:27:09,572 ERROR   MainThread:35360 [wandb_init.py:init():583] backend process timed out
2022-01-05 21:27:09,572 ERROR   MainThread:35360 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-01-05 21:29:03,720 INFO    MainThread:35360 [wandb_init.py:teardown():219] tearing down wandb.init
